Layout/LineLength:
  Max: 100

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Max: 110

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
