st1 = Station.new("Pavshino")
st2 = Station.new("Lyubertsy")
st3 = Station.new("Ab")
st4 = Station.new("Ac")
st5 = Station.new("Ad")
st6 = Station.new("Ae")
st7 = Station.new("Zx")
st8 = Station.new("Zy")
st9 = Station.new("Zv")
st10 = Station.new("Lyubertsy")
route1 = Route.new("Pavshino", "Lyubertsy")
route2 = Route.new("Lyubertsy", "Pavshino")
route1.add_between(st3)
route1.add_between(st4)
route1.add_between(st5)
route1.add_between(st6)
route2.add_between(st7)
route2.add_between(st8)
route2.add_between(st9)
route2.add_between(st10)
tr1 = Train.new("13", "gruz", 6)
tr2 = Train.new("14", "pass", 3)
tr3 = Train.new("15", "pass", 7)
st1.accept_train(tr1)
st2.accept_train(tr2)
st2.accept_train(tr3)
tr1.accept_route(route1)
tr2.accept_route(route2)
tr3.accept_route(route2)
puts tr1.current_station
puts tr2.current_station
puts tr3.current_station
puts tr1.next_station
puts tr1.previous_station
tr1.move("forward")
puts tr1.current_station
